pages:
  image: node:18
  stage: build
  script:
    - npm install --progress=false
    - npm run build
    - cp -r dist/* public/
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  tags:
  - node
  when: manual
